name: Check

on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Maven Package
        run: mvn -B clean test
      - name: "telegram Notification"
        if: ${{ success() }}
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Tests ${{ job.status }}
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message}}
            
            Repository: ${{ github.repository }}
          
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            - name: Telegram notification
      - name: "telegram Notification"
        if: ${{ failure() }}
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Tests failed |
            curl -s -X POST https://api.telegram.org/bot7094090150:AAFZ2QeDf4-RFVI_ouaMN6KcNmmCJgQLsv0/sendMessage -d chat_id=871489705 -d text="Tests failed, please check the logs for more information"
